apiVersion: v1
kind: Service
metadata:
  name: security-agent
  labels:
    {{- include "cloud-security-scanner.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend-alias
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
