apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-init
  labels:
    {{- include "cloud-security-scanner.labels" . | nindent 4 }}
data:
  {{- $files := .Files }}
  {{- range $path, $_ := .Files.Glob "sql/*.sql" }}
  {{ base $path }}: |
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
