apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{- include "cloud-security-scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.password | quote }}
  jwt-secret: {{ .Values.backend.jwtSecret | quote }}
  minio-root-user: {{ .Values.minio.rootUser | quote }}
  minio-root-password: {{ .Values.minio.rootPassword | quote }}
  admin-username: {{ .Values.app.adminUsername | quote }}
  admin-password: {{ .Values.app.adminPassword | quote }}
  encryption-key: {{ .Values.app.encryptionKey | default "K8sSecureEncKey32CharactersLong!" | quote }}
